# Default values for Victoria Logs

replicaCount: 1

image:
  repository: victoriametrics/victoria-logs
  tag: v0.9.3
  pullPolicy: IfNotPresent

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: victoria-logs.local
      paths:
        - path: /
          pathType: Prefix

service:
  type: ClusterIP
  port: 9428
  targetPort: 9428

persistence:
  enabled: true
  storageClass: "local-storage"
  size: 50Gi

resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 200m
    memory: 512Mi

# Victoria Logs configuration
config:
  retentionPeriod: "1y"
  maxDiskUsagePerSearch: 0
  loggerDisableTimestamps: true
  loggerFormat: json
  httpListenAddr: :9428

# Agent (similar to Promtail) configuration
agent:
  enabled: true
  replicaCount: 2
  image:
    repository: victoriametrics/victoria-logs-agent
    tag: v0.9.3
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  config:
    scrapePaths:
      - /var/log/*.log
      - /var/log/syslog
      - /var/log/messages
    labels:
      job: victoria-logs-agent
      env: production