apiVersion: v2
name: postgres-operator
description: A Helm chart for Zalando's Postgres Operator
type: application
version: 0.1.0
appVersion: "1.14.0"
home: https://github.com/zalando/postgres-operator
sources:
  - https://github.com/zalando/postgres-operator
maintainers:
  - name: Web3 Message Board Team
dependencies:
  - name: postgres-operator
    version: "1.14.0"
    repository: https://opensource.zalando.com/postgres-operator/charts/postgres-operator
  - name: postgres-operator-ui
    version: "1.14.0"
    repository: https://opensource.zalando.com/postgres-operator/charts/postgres-operator-ui
    condition: ui.enabled