---
# Handlers for Nginx role

- name: Restart Nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    daemon_reload: yes

- name: Reload Nginx
  ansible.builtin.systemd:
    name: nginx
    state: reloaded
