---
# Node.js installation for all platforms

- name: Set Node.js version
  set_fact:
    node_version: "{{ node_version | default('18') }}"

# Ubuntu 24.04 uses the official script method
- name: Install Node.js (Ubuntu 24.04)
  block:
    - name: Install Node.js deps
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
        state: present
      become: true

    - name: Install Node.js using official script for Ubuntu 24.04
      shell: |
        set -e
        curl -fsSL https://deb.nodesource.com/setup_{{ node_version }}.x | sudo -E bash -
        sudo apt-get install -y nodejs
      args:
        executable: /bin/bash
        creates: /usr/bin/node
      become: true
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_release == "noble"
    - not is_macos | bool
    - sudo_access.rc == 0

# Standard installation for other Debian/Ubuntu
- name: Install Node.js (Standard Debian/Ubuntu)
  block:
    - name: Install Node.js repository key
      apt_key:
        url: https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key
        state: present
      become: true

    - name: Add Node.js repository
      apt_repository:
        repo: "deb https://deb.nodesource.com/node_{{ node_version }}.x {{ ansible_distribution_release }} main"
        state: present
      become: true

    - name: Install Node.js
      package:
        name: nodejs
        state: present
      become: true
  when:
    - ansible_os_family == "Debian"
    - not (ansible_distribution == "Ubuntu" and ansible_distribution_release == "noble")
    - not is_macos | bool
    - sudo_access.rc == 0

# For macOS
- name: Install Node.js (macOS)
  homebrew:
    name: node@{{ node_version }}
    state: present
  when:
    - is_macos | bool

- name: Verify Node.js installation
  shell: "node -v"
  register: node_version_output
  changed_when: false

- name: Display Node.js version
  debug:
    var: node_version_output.stdout
