---
# Tasks for installing Terraform

- name: Add HashiCorp GPG key
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    keyring: /usr/share/keyrings/hashicorp-archive-keyring.gpg
    state: present
  become: true
  when: ansible_os_family == "Debian"

- name: Add HashiCorp repository
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
    state: present
  become: true
  when: ansible_os_family == "Debian"

- name: Install Terraform
  apt:
    name: terraform
    state: present
    update_cache: yes
  become: true
  when: ansible_os_family == "Debian"

- name: Verify Terraform installation
  command: terraform --version
  register: terraform_version
  changed_when: false

- name: Display Terraform version
  debug:
    var: terraform_version.stdout_lines[0]