---
apiVersion: v2
name: monad-monitoring
description: A Helm chart for Loki and Grafana logging stack
type: application
version: 0.1.0
appVersion: "1.0.0"
icon: https://raw.githubusercontent.com/grafana/grafana/main/public/img/grafana_icon.svg

# Dependencies
dependencies:
  - name: loki-stack
    version: "^2.10.2"
    repository: "https://grafana.github.io/helm-charts"
    condition: lokiStack.enabled
  - name: grafana
    version: "^8.11.1"
    repository: "https://grafana.github.io/helm-charts"
    condition: grafana.enabled
  - name: minio
    version: "5.4.0"
    repository: "https://charts.min.io/"
    condition: minio.enabled
