---
galaxy_info:
  author: Jonathon Fritz
  description: Manages system services
  company: Nextwave
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - service
    - systemd
    - management
    - system

dependencies: []
