---
# Default variables for the GitHub Actions dependencies role

# Project root directory (defaults to current working directory)
project_root: "{{ ansible_env.PWD }}"

# Go installation
go_version: "1.23" # Default Go version as seen in workflows
go_install_dir: "/usr/local/go"

# Node.js installation
node_version: "20" # Default Node.js version as seen in workflows

# pnpm installation
pnpm_version: "8" # Default pnpm version as seen in workflows

# Whether to install specific dependency groups
install_go: true
install_node: true
install_pnpm: true
install_ansible: true
install_github_cli: true
