---
apiVersion: v2
name: minio-storage
description: A Helm chart for MinIO object storage
type: application
version: 0.1.0
appVersion: "1.0.0"
icon: https://min.io/resources/img/logo/MINIO_wordmark.png

# Dependencies
dependencies:
  - name: minio
    version: "5.4.0"
    repository: "https://charts.min.io/"