---
# Playbook for setting up GitHub Actions runner dependencies
# This playbook installs all the necessary dependencies for running GitHub workflow jobs

- name: Install GitHub Actions runner dependencies
  hosts: github_runners
  become: false
  gather_facts: true
  vars:
    # Override defaults if needed
    go_version: "1.22.1"
    node_version: "20"
    pnpm_version: "8"

    # Control which dependency sets to install
    install_go: true
    install_node: true
    install_pnpm: true
    install_ansible: true
    install_github_cli: true
    install_govmomi: true
    install_helm: true
    install_rustscan: true
    install_artillery: true
    install_terraform: true

    # Kubernetes configuration
    install_kubectl: true
    kubectl_version: "v1.31.0"
    setup_kubernetes: "{{ lookup('env', 'SETUP_KUBERNETES') | default(false) | bool }}"
    kubeconfig_content: "{{ lookup('env', 'KUBECONFIG_CONTENT') | default('') }}"

    # Project root directory
    project_root: "{{ lookup('env', 'HOME') }}/ansible_runner_env"

  roles:
    - role: github_actions_deps
