---
name: Test CI Structure

on:
  workflow_dispatch:

jobs:
  test:
    name: Test CI Organization
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print directory structure
        run: |
          echo "Current CI directory structure:"
          find .github/workflows/ci -type f | sort

      - name: Verify yamllint configuration
        run: |
          pip install yamllint
          yamllint --version
          cat .yamllint.yaml
